### ISSUE TITLE
(Carbon) Game stays resident in memory and has to be terminated through task manager

### ISSUE THREAD

**Issue by TorutheRedFox** [xan1242/NFS-XtendedInput#15]
Not sure about other games, but when you exit the game, the window closes as it should, but the process never actually exits, making you have to terminate it in taskmgr

**Comment by HarGabt** [comment]
Weird. Doesn't happen on my end, tried exiting with Q and Alt-F4.
Are there any other mods you have installed that may force this game to stay in memory?

**Comment by ToruTheRedFox** [comment]
I removed the asi from the scripts folder and it terminates normally

**Comment by HarGabt** [comment]
Have you tried newer versions of the mod?

**Comment by ToruTheRedFox** [comment]
if it is, then it's moreso an issue with the code here than the library as it shouldn't do that, and the newer library is just being more lenient (which may not be the case in WINE and such)

**Comment by xan1242** [comment]
Can't replicate even with 9.1.0 either.

The issue is on your end. Besides, 9.1.0 builds aren't supported by me right now, so I won't take this issue into consideration since you're running non-release or non-upstream code anyway.

**Comment by TorutheRedFox** [comment]
ok revisiting this, I found something odd

if I uncomment the console window related stuff, the game actually closes fully when I close the console window

**Comment by xan1242** [comment]
Again, no idea why it happens to you.

I've disabled all test prints for the release builds anyway as you can see,
so if console attaching and/or reopening fixes it, then something is still
accessing the console for you.

But it is true that the game in general behaves much better with it.

Maybe try launching without the console window, but through a debugger
instead. See if that fixes it or, better yet, reveals the issue.
-- 
*Lovro Pleše*

**Comment by xan1242** [comment]
I even tested it out with DSOAL, can't replicate it on my end no matter what I do.  Can't help you with this one, sorry.

**Comment by TorutheRedFox** [comment]
what version of OpenAL-Soft are you using with it?

I'm using 1.19.1
