### ISSUE TITLE
(Carbon) mapping FRONTENDACTION_BUTTON0 and FRONTENDACTION_BUTTON1 to the triggers to match PS3 leaves them unresponsive

### ISSUE THREAD

**Issue by TorutheRedFox** [xan1242/NFS-XtendedInput#16]
the game doesn't respond to these actions if they're mapped to analog inputs it seems

**Comment by xan1242** [comment]
fixed in [dc1e1ad](https://github.com/xan1242/NFS-XtendedInput/commit/dc1e1ad1f300ab54977395be3bfaa06e29f152a4)

Closing.
