### ISSUE TITLE
Showcase button prompt switches back to PC version for a frame when selecting different car

### ISSUE THREAD

**Issue by ToruTheRedFox** [xan1242/NFS-XtendedInput#4]

**Comment by HarGabt** [comment]
It's a known issue.
https://github.com/xan1242/NFS-XtendedInput/blob/2e8f20b096db02e7d042ed07d43bc8b68f5e4617/dllmain.cpp#L11

**Comment by AeroWidescreen** [comment]
I've asked him if he could add an option to disable the switching entirely. I think it would be an acceptable workaround for the time being. And I'm sure there are some people (like myself) who don't want it to switch at all. We'll see what he does...

**Comment by xan1242** [comment]
It could be an option to entirely disable dynamic switching and just make it quack like the console version. Just swap the flags it hides with the PC ones and it's basically the console version then.

I'll take a look. Hopefully after Carbon is fully finished.

**Comment by xan1242** [comment]
fixed in [51de979](https://github.com/xan1242/NFS-XtendedInput/commit/51de97921d90218594e1b49450ae6a5cd67558dd)

Feature to disable switching was also added.

Closing.
