### ISSUE TITLE
ug2 shift up down still cant bind on rightstick and i cant cancel. keybord does move has to kill program

### ISSUE THREAD

**Issue by Ninotchkaooo** [xan1242/NFS-XtendedInput#46]
ug1 work perfect

**Comment by HarGabt** [comment]
Wrong repository, bud.
[Check this one.](https://github.com/xan1242/NFS-XtendedInput/)

**Comment by xan1242** [comment]
You've given the wrong link, but that's not of concern...

I've released a new version: https://github.com/xan1242/NFSU-XtendedInput/releases/tag/2.7

Try it and if there still are issues, open the issue in [this repository](https://github.com/xan1242/NFSU-XtendedInput) instead.
