### ISSUE TITLE
(Carbon) crash on startup?

### ISSUE THREAD

**Issue by ToruTheRedFox** [xan1242/NFS-XtendedInput#5]

**Comment by xan1242** [comment]
Not an issue, you're missing the TPK file for Carbon. If you built this yourself, you need to build the TPK for Carbon too, which I did not release yet. 

Carbon is still WIP anyway so I won't accept issues for it until I release it.

**Comment by ToruTheRedFox** [comment]
it seems the version you have on GitHub is out of date?
