### ISSUE TITLE
ProStreet patch prevents game from launching correctly under certain circumstances

### ISSUE THREAD

**Issue by IryRasmo** [xan1242/NFS-XtendedInput#55]
I have the cracked version from oldgamesdownload (sue me) and followed the tutorial found from [this Reddit post](https://www.reddit.com/r/needforspeed/comments/st8ato/nfs_pro_street_2022_fix/) to get it to run correctly on my system. Currently installed in the scripts folder are MultiFix and Extra Options. Both the normal and Win7 versions of XtendedInput have prevented the game from running at all; it loads to a black screen with the ProStreet cursor, then exits. Not sure if I'm justified in making a bug report but there may be an issue

**Comment by IryRasmo** [comment]
installed the fucker wrong nvm

**Comment by IryRasmo** [comment]
NVM NVM
I DID NOT INSTALL IT WRONG IT JUST DOESNT WORK RIGHT

**Comment by xan1242** [comment]
First of all, MultiFix is old. Use GenericFix instead: https://thirteenag.github.io/wfp#nfs

For Pro Street, you have to install it in a specific order:

1. Install from the original installer (disc iso)
2. Determine which version you have by the installer - when it asks you for the language, if it offers only English and Spanish, it's the US build, if it's any other, it's probably the EU build
3. Download the correct patch for your region
4. Apply the said patch
5. Put the No CD fix by Battery: [nfs_battery.zip](https://github.com/xan1242/NFS-XtendedInput/files/10778106/nfs_battery.zip)
6. Check if the game works without any patches
7. Install GenericFix, XtendedInput, etc.

I went through these steps with someone else not too long ago and the game worked for them properly after these steps.

Just for a sanity check I re-downloaded the release ZIP and put it in, it works for me just fine.

**Comment by IryRasmo** [comment]
Got the thing to work after a little finagling! Thanks for the help and sorry for the trouble lmao
