### ISSUE TITLE
[MW] Disconnecting controller dialog box causes softlock the game

### ISSUE THREAD

**Issue by RostovShev03** [xan1242/NFS-XtendedInput#58]
After 15-20 minutes without pressing any button on Xbox controller, it disconnects, but when the game attempts show disconnecting massage dialog box, it completely goes softlock.  I think it also happens in Carbon, Undercover.

**Comment by xan1242** [comment]
I know it's broken. It's not a finished feature as I've only targeted Pro Street for it.

Carbon works by extension, but without the string update.

**Comment by xan1242** [comment]
BTW, you can press the "start" button (4 by default on the KB) to dismiss it. Same goes for the pause menu.

**Comment by xan1242** [comment]
Not a bug anymore - you can press FRONTENDACTION_START to dismiss the menu and optionally disable the feature with `PassConnStatus`
