### ISSUE TITLE
Console UI style but with Keyboard

### ISSUE THREAD

**Issue by longaru** [xan1242/NFS-XtendedInput#60]
Hey Bro , after update to 1.17 - input with keyboard don't work with : 
FirstControlDevice = 1
UseDynamicFEngSwitching = 0

1 & 0 values - permanently enables UI from Consoles for MW , CA , PS and works with keyboard at 1.16 very well ( and lower versions ) . But not in 1.17 ... Why You change it :(

I really love this feature , looks very cool ... it's just dream . And I hate PC's UI ( Enter , Back etc with separately quads )

What about create & add new PC's icons ( that aero_ does ) for Console UI style ?

**Comment by TorutheRedFox** [comment]
honestly, fair

the PC prompts in Carbon and ProStreet look horrible compared to their console counterparts

MW looks somewhat alright as it's a similar style to the rest of the UI, but the rest (especially Carbon) are just no

**Comment by xan1242** [comment]
Use 1.16 in the meantime.

1.17 was targeted at Pro Street controller disconnection. No new features otherwise, so you're not missing out on anything.

**Comment by xan1242** [comment]
fixed in: https://github.com/xan1242/NFS-XtendedInput/commit/e6a1749d0bba1c0c3d2b5aec623b76aa1ba4594e
