### ISSUE TITLE
Controls are swapped, but ini file seems to be fine

### ISSUE THREAD

**Issue by JohnSmith2007** [xan1242/NFS-XtendedInput#61]
I'm using a Dualshock 4 PS4 controller, plugged in via USB. For some reason, the "O" and "Option" buttons are swapped. But when I look at the ini file (NFS_XtendedInput.ini), nothing seems to be out of place. What the hell?!

**Comment by xan1242** [comment]
Hello, I've made a new release.

Please try it out and report back.

https://github.com/xan1242/NFS-XtendedInput/releases/tag/1.18

**Comment by xan1242** [comment]
Closing this issue. If you still have the problem, open the issue again.
