### ISSUE TITLE
[Most Wanted] Controller removed screen softlock

### ISSUE THREAD

**Issue by ambient7** [xan1242/NFS-XtendedInput#69]
When the controller disconnects and the "Controller removed" screen shows up i can´t do anything to dismiss it and continue playing. Only close the game.
Pressing start only worked once 
![20230707122929_1](https://github.com/xan1242/NFS-XtendedInput/assets/76193987/2b22d98a-9b6a-4c85-a2c4-61ba2fcd4954)

**Comment by xan1242** [comment]
fixed it in: https://github.com/xan1242/NFS-XtendedInput/commit/861b6c17ba3dc072b15e7a65c5e86d1aa9699fc6

Get the build here: https://github.com/xan1242/NFS-XtendedInput/releases/tag/1.19
