### ISSUE TITLE
ignore hotkeys (i.e. f12) when polling keyboard to switch button prompts

### ISSUE THREAD

**Issue by ToruTheRedFox** [xan1242/NFS-XtendedInput#7]

**Comment by xan1242** [comment]
Don't understand the context behind this one.

You mean ignore the key (as in make it not bindable) or disable screenshot functionality?

I've noted this previously, but some hardcoded functions were NOT touched and this includes keyboard actions.

**Comment by ToruTheRedFox** [comment]
as in

**Comment by xan1242** [comment]
Not sure why would you want that though? A keyboard button press is a keyboard button press, no matter if it's a hotkey. It is counter-intuitive to do what you're suggesting.

If there's a hotkey you're missing and want to bind to a controller button then let me know. 

I will not consider this to be a relevant issue either way.

**Comment by ToruTheRedFox** [comment]
I meant don't switch the prompts if you're just taking a screenshot or whatever as that's kinda...

nonsensical? (also a bit annoying if you're trying to show them off xd)

**Comment by xan1242** [comment]
It makes even less sense to kill binds over things like screenshots.

The only solution to this issue would be [this](https://github.com/xan1242/NFS-XtendedInput/blob/311d04090cb3f03b5fe6285f35e9da88d22a04da/NFS_XtendedInput_FEng.h#L34) which I've already implemented.

Either that or take a screenshot in a different way. I will not be disabling keybinds. That's all I have to say about this.
