### ISSUE TITLE
Allow players to map the clutch in NFS Carbon

### ISSUE THREAD

**Issue by ziidonato** [xan1242/NFS-XtendedInput#70]
In the widescreen fix, they give you the option for expanded controller options, which lets you map just about everything you can map in the game. One of the options is the clutch.

I'm using this mod because it makes it easy to set up careers for speedrunning without having to map the controller over & over again. I'm not that good, but control of the clutch is supposed to be essential to faster track times. So please let the player map the clutch option in NFSC.

**Comment by xan1242** [comment]
Per the EventReference, `GAMEACTION_CLUTCH` is available in Carbon.

You may map this to any button in the ini. 

Example, mapping it to the B button on the controller (under Events): `GAMEACTION_CLUTCH = XINPUT_GAMEPAD_B`

Another example, mapping it to the space on the keyboard (under EventsKB): `GAMEACTION_CLUTCH = VK_SPACE`

I have planned to implement ingame options menu functionality and I'll do it when I get to it.

**Comment by ziidonato** [comment]
Oh, I probably read it wrong then. I thought there were some options that were only available in prostreet. My bad :)
