### ISSUE TITLE
[NFS: PS] XtendedInput not working

### ISSUE THREAD

**Issue by WhiscasKaat** [xan1242/NFS-XtendedInput#72]
I installed the game from OldGamesDownload, and then I installed the Generic Fix, and the game worked just fine, but the moment I add the XtendedInput files the game doesn't want to launch
Am I doing something wrong?

**Comment by WhiscasKaat** [comment]
Update: My game works just fine now, I think it didn't work because I didn't install the 1.1 patch
After I installed the patch, the issue was solved

**Comment by xan1242** [comment]
Yeah this only supports 1.1. I hadn't implemented pattern detection so it works with other versions.

That it something I'll consider in the future, but for now, everyone plays 1.1.
