### ISSUE TITLE
NFS Undercover: HUDACTION_PAUSEREQUEST = XINPUT_GAMEPAD_START doesn't work

### ISSUE THREAD

**Issue by RostovShev03** [xan1242/NFS-XtendedInput#81]
Hello there! In the latest version of Xtended input I noticed that HUDACTION_PAUSEREQUEST = XINPUT_GAMEPAD_START doesn't work at all in NFS Undercover. Please, explain me: what could be wrong? In other NFS games it works flawlessly

**Comment by Lumanator** [comment]
I can confirm I have the same issue. Strangely, it works on the map screen.

**Comment by xan1242** [comment]
Fixed by https://github.com/xan1242/NFS-XtendedInput/commit/6c8248d209f6de8e2a418992b61a5b8385716757
