### ISSUE TITLE
Gamepad Icons appear blurry in NFSC

### ISSUE THREAD

**Issue by WROOBELEK** [xan1242/NFS-XtendedInput#9]
https://prnt.sc/rJNI6g6i7Qg4

**Comment by xan1242** [comment]
Increase your texture quality (world quality) then and try again. This is loaded natively through the game so you're probably seeing mipmaps because the game decided to lower the general quality of the textures.

@AeroWidescreen maybe you could drop mipmaps altogether or just limit it to minimum 32x32 during export?

**Comment by AeroWidescreen** [comment]
> BTW this shouldn't just affect NFSC, but all others as well, technically speaking.

It does affect NFSMW, but not as significantly. Carbon seems to be a lot more aggressive for some reason.

![NFSMW](https://i.imgur.com/1uMXbDI.png)
![NFSC](https://i.imgur.com/hJHvZAW.png)

Anyway, forcing the lowest mipmap to be 32x32 sounds like a smart compromise.

**Comment by xan1242** [comment]
@WROOBELEK test with [the latest release](https://github.com/xan1242/NFS-XtendedInput/releases/tag/1.4), it should work now

**Comment by WROOBELEK** [comment]
It's better now. I also have an unrelated question, graphic settings do not save after changing in NFS C & NFS PS. Why?

**Comment by HarGabt** [comment]
Tested it, looks good enough on 1080p.
![Need for Speed Carbon_2022 04 29-21 51](https://user-images.githubusercontent.com/44652400/165997178-fb320eed-6240-46ef-8026-e1fbdb623285.png)

**Comment by xan1242** [comment]
> It's better now. I also have an unrelated question, graphic settings do not save after changing in NFS C & NFS PS. Why?

You're probably running under UAC. This game, by default, saves settings in the registry. I suggest you enable WS fix's "WriteSettingsToFile" option to fix your problem.

Or you can run the game as administrator. Whichever suits your fancy.

In any case, thank you and HarGabt for confirming it works, closing.

**Comment by ToruTheRedFox** [comment]
best part about this is that at 720p and max settings, they're almost _too_ sharp

**Comment by xan1242** [comment]
> best part about this is that at 720p and max settings, they're almost _too_ sharp

128x128 is a perfect balance for today's hardware. Anything lower, it's a risk of being too blurry.

There isn't a simple solution to this issue other than incorporating some form of scale filter or shader which would mitigate the issue. Plausible, but out of scope for this project.
